def write_into_html(testo):
    with open("download.html", "a", encoding="utf-8") as f:
        f.write(f"\n{testo}")
        return

def generate_html(lista_blocchi, layout, colore_sfondo):
    with open("download.html", "w", encoding="utf-8") as f:
        f.write(
            "<!DOCTYPE html>\n"
            "<html lang=\"it\">\n"
            "<head>\n"
            "    <meta charset=\"UTF-8\">\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            "    <title>WebSite by WebOne Generator</title>\n"
            "    <style>\n"
            "/* Reset e Base - Apple Minimal Style */\n"
            "* {\n"
            "    margin: 0;\n"
            "    padding: 0;\n"
            "    box-sizing: border-box;\n"
            "}\n"
            "\n"
            "body {\n"
            "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif;\n"
            "    background-color: #f8f9fa;\n"
            "    color: #1d1d1f;\n"
            "    line-height: 1.6;\n"
            "    padding: 2rem;\n"
            "    display: flex;\n"
            "    flex-direction: column;\n"
            "}\n"
            "\n"
            "/* Container principale a due colonne */\n"
            ".main-container {\n"
            "    display: flex;\n"
            "    gap: 2rem;\n"
            "    flex: 1;\n"
            "}\n"
            "\n"
            ".left-column {\n"
            "    flex: 1;\n"
            "    min-width: 0;\n"
            "}\n"
            "\n"
            ".right-column {\n"
            "    flex: 1;\n"
            "    min-width: 0;\n"
            "}\n"
            "\n"
            "/* Titoli - Compatti e eleganti */\n"
            "h1 {\n"
            "    font-size: 1.8rem;\n"
            "    font-weight: 700;\n"
            "    color: #1d1d1f;\n"
            "    margin: 0 0 1rem 0;\n"
            "    letter-spacing: -0.5px;\n"
            "}\n"
            "\n"
            "h2 {\n"
            "    font-size: 1.2rem;\n"
            "    font-weight: 600;\n"
            "    color: #1d1d1f;\n"
            "    margin: 1rem 0 0.6rem 0;\n"
            "    letter-spacing: -0.3px;\n"
            "}\n"
            "\n"
            "h3 {\n"
            "    font-size: 1rem;\n"
            "    font-weight: 600;\n"
            "    color: #424245;\n"
            "    margin: 0 0 0.8rem 0;\n"
            "}\n"
            "\n"
            "/* Paragrafi e testo - Scuro per leggibilità */\n"
            "p {\n"
            "    color: #424245;\n"
            "    margin-bottom: 0.4rem;\n"
            "    font-size: 0.9rem;\n"
            "}\n"
            "\n"
            "/* Link - Stile minimal */\n"
            "a {\n"
            "    color: #0071e3;\n"
            "    text-decoration: none;\n"
            "    transition: color 0.2s ease;\n"
            "    cursor: pointer;\n"
            "}\n"
            "\n"
            "a:hover {\n"
            "    color: #0077ed;\n"
            "}\n"
            "\n"
            "/* Header / Top bar */\n"
            ".header-toolbar {\n"
            "    display: flex;\n"
            "    align-items: center;\n"
            "    justify-content: space-between;\n"
            "    margin-bottom: 1.5rem;\n"
            "    gap: 1rem;\n"
            "    flex-wrap: wrap;\n"
            "    padding-bottom: 1rem;\n"
            "    border-bottom: 1px solid #e5e5e7;\n"
            "}\n"
            "\n"
            ".header-toolbar a {\n"
            "    display: inline-block;\n"
            "    padding: 0.5rem 1rem;\n"
            "    background-color: #0071e3;\n"
            "    color: white;\n"
            "    border-radius: 6px;\n"
            "    font-weight: 500;\n"
            "    font-size: 0.9rem;\n"
            "    transition: background-color 0.2s ease;\n"
            "}\n"
            "\n"
            ".header-toolbar a:hover {\n"
            "    background-color: #0077ed;\n"
            "    color: white;\n"
            "}\n"
            "\n"
            "/* Toolbar aggiunta elementi */\n"
            ".toolbar-aggiunta {\n"
            "    display: grid;\n"
            "    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));\n"
            "    gap: 0.8rem;\n"
            "    margin-bottom: 1.5rem;\n"
            "}\n"
            "\n"
            ".toolbar-aggiunta form {\n"
            "    display: flex;\n"
            "    gap: 0.4rem;\n"
            "}\n"
            "\n"
            ".toolbar-aggiunta input[type=\"file\"] {\n"
            "    flex: 1;\n"
            "}\n"
            "\n"
            ".toolbar-aggiunta button {\n"
            "    flex-shrink: 0;\n"
            "}\n"
            "\n"
            "/* Form e Input */\n"
            "form {\n"
            "    margin: 0;\n"
            "    display: flex;\n"
            "    flex-direction: column;\n"
            "    gap: 0.6rem;\n"
            "}\n"
            "\n"
            "form.inline {\n"
            "    flex-direction: row;\n"
            "    align-items: flex-end;\n"
            "    gap: 0.6rem;\n"
            "}\n"
            "\n"
            "input[type=\"text\"],\n"
            "input[type=\"file\"],\n"
            "select {\n"
            "    padding: 0.6rem;\n"
            "    border: 1px solid #d2d2d7;\n"
            "    border-radius: 6px;\n"
            "    font-size: 0.9rem;\n"
            "    background-color: #ffffff;\n"
            "    color: #1d1d1f;\n"
            "    transition: border-color 0.2s ease;\n"
            "    font-family: inherit;\n"
            "}\n"
            "\n"
            "textarea {\n"
            "    padding: 0.6rem;\n"
            "    border: 1px solid #d2d2d7;\n"
            "    border-radius: 6px;\n"
            "    font-size: 0.9rem;\n"
            "    background-color: #ffffff;\n"
            "    color: #1d1d1f;\n"
            "    transition: border-color 0.2s ease;\n"
            "    font-family: inherit;\n"
            "    resize: vertical;\n"
            "    min-height: 60px;\n"
            "}\n"
            "\n"
            "input[type=\"text\"]::placeholder,\n"
            "textarea::placeholder {\n"
            "    color: #86868b;\n"
            "}\n"
            "\n"
            "input[type=\"text\"]:focus,\n"
            "input[type=\"file\"]:focus,\n"
            "select:focus,\n"
            "textarea:focus {\n"
            "    outline: none;\n"
            "    border-color: #0071e3;\n"
            "    box-shadow: 0 0 0 3px rgba(0, 113, 227, 0.1);\n"
            "}\n"
            "\n"
            "/* Label */\n"
            "label {\n"
            "    color: #1d1d1f;\n"
            "    font-weight: 600;\n"
            "    font-size: 0.9rem;\n"
            "}\n"
            "\n"
            "/* Bottoni */\n"
            "button {\n"
            "    padding: 0.6rem 1.2rem;\n"
            "    border: none;\n"
            "    border-radius: 6px;\n"
            "    font-size: 0.9rem;\n"
            "    font-weight: 600;\n"
            "    cursor: pointer;\n"
            "    transition: all 0.2s ease;\n"
            "    background-color: #0071e3;\n"
            "    color: white;\n"
            "    white-space: nowrap;\n"
            "}\n"
            "\n"
            "button:hover {\n"
            "    background-color: #0077ed;\n"
            "}\n"
            "\n"
            "button:active {\n"
            "    opacity: 0.8;\n"
            "}\n"
            "\n"
            "button[formaction=\"/elimina\"],\n"
            "button[style*=\"background-color: #ff4444\"] {\n"
            "    background-color: #ff3b30;\n"
            "    color: white !important;\n"
            "}\n"
            "\n"
            "button[formaction=\"/elimina\"]:hover,\n"
            "button[style*=\"background-color: #ff4444\"]:hover {\n"
            "    background-color: #ff453a;\n"
            "}\n"
            "\n"
            ".btn-reset {\n"
            "    background-color: #ff3b30 !important;\n"
            "    width: 100% !important;\n"
            "}\n"
            "\n"
            ".btn-reset:hover {\n"
            "    background-color: #ff453a !important;\n"
            "}\n"
            "\n"
            "/* Contenitore lavoro */\n"
            ".area-di-lavoro {\n"
            "    background: #ffffff;\n"
            "    border-radius: 8px;\n"
            "    padding: 1.5rem;\n"
            "    border: 1px solid #e5e5e7;\n"
            "    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);\n"
            "}\n"
            "\n"
            "/* Contenitore impostazioni (colore sfondo, ecc) */\n"
            ".settings-bar {\n"
            "    display: flex;\n"
            "    align-items: flex-end;\n"
            "    gap: 0.8rem;\n"
            "    margin-bottom: 1.5rem;\n"
            "    flex-wrap: wrap;\n"
            "}\n"
            "\n"
            ".settings-bar form {\n"
            "    flex: 1;\n"
            "    min-width: 200px;\n"
            "}\n"
            "\n"
            ".settings-bar form.inline {\n"
            "    flex-direction: row;\n"
            "}\n"
            "\n"
            ".settings-bar label {\n"
            "    margin: 0;\n"
            "}\n"
            "\n"
            ".settings-bar select {\n"
            "    flex: 1;\n"
            "}\n"
            "\n"
            ".settings-bar button {\n"
            "    flex-shrink: 0;\n"
            "}\n"
            "\n"
            "/* Blocchi - Stile work-in-progress con dashed border */\n"
            ".blocco-editor {\n"
            "    border: 2px dashed #d2d2d7;\n"
            "    background-color: #fafafa;\n"
            "    border-radius: 8px;\n"
            "    transition: all 0.2s ease;\n"
            "    padding: 1rem;\n"
            "    margin: 0 0 0.8rem 0;\n"
            "}\n"
            "\n"
            ".blocco-editor:hover {\n"
            "    border-color: #0071e3;\n"
            "    background-color: #ffffff;\n"
            "    box-shadow: 0 2px 8px rgba(0, 113, 227, 0.08);\n"
            "}\n"
            "\n"
            ".blocco-editor.blocco-immagine {\n"
            "    display: flex;\n"
            "    flex-direction: column;\n"
            "}\n"
            "\n"
            ".blocco-preview-image {\n"
            "    width: 40px;\n"
            "    height: 40px;\n"
            "    object-fit: cover;\n"
            "    border-radius: 4px;\n"
            "    border: 1px solid #d2d2d7;\n"
            "}\n"
            "\n"
            ".blocco-file-info {\n"
            "    font-size: 0.75rem;\n"
            "    color: #86868b;\n"
            "    margin: 0;\n"
            "    word-break: break-all;\n"
            "}\n"
            "\n"
            ".blocco-editor-header {\n"
            "    display: flex;\n"
            "    justify-content: space-between;\n"
            "    align-items: center;\n"
            "    margin-bottom: 0.6rem;\n"
            "    gap: 0.8rem;\n"
            "    flex-wrap: wrap;\n"
            "}\n"
            "\n"
            ".blocco-info {\n"
            "    display: flex;\n"
            "    gap: 1rem;\n"
            "    flex-wrap: wrap;\n"
            "}\n"
            "\n"
            ".blocco-info p {\n"
            "    margin: 0;\n"
            "    min-width: 120px;\n"
            "}\n"
            "\n"
            ".blocco-editor-form {\n"
            "    display: flex;\n"
            "    flex-direction: column;\n"
            "    gap: 0.6rem;\n"
            "}\n"
            "\n"
            ".blocco-editor-controls {\n"
            "    display: grid;\n"
            "    grid-template-columns: repeat(auto-fit, minmax(90px, 1fr));\n"
            "    gap: 0.6rem;\n"
            "    margin-top: 0.8rem;\n"
            "}\n"
            "\n"
            ".blocco-editor-controls button {\n"
            "    padding: 0.6rem 0.8rem;\n"
            "    font-size: 0.85rem;\n"
            "}\n"
            "\n"
            "/* Fallback per blocchi vecchi (inline styles) */\n"
            "div[style*=\"border: 1px dashed black\"] {\n"
            "    border: 2px dashed #d2d2d7 !important;\n"
            "    background-color: #fafafa !important;\n"
            "    border-radius: 8px !important;\n"
            "    transition: all 0.2s ease;\n"
            "    padding: 1.2rem !important;\n"
            "    margin: 0 0 1rem 0 !important;\n"
            "}\n"
            "\n"
            "div[style*=\"border: 1px dashed black\"]:hover {\n"
            "    border-color: #0071e3 !important;\n"
            "    background-color: #ffffff !important;\n"
            "    box-shadow: 0 2px 8px rgba(0, 113, 227, 0.08) !important;\n"
            "}\n"
            "\n"
            "div[style*=\"border: 1px dashed black\"] p {\n"
            "    color: #424245;\n"
            "    font-size: 0.95rem;\n"
            "}\n"
            "\n"
            "/* Immagine */\n"
            ".image {\n"
            "    width: 100%;\n"
            "    max-width: 250px;\n"
            "    display: block;\n"
            "    border-radius: 8px;\n"
            "    border: 1px solid #e5e5e7;\n"
            "    margin: 1rem 0;\n"
            "}\n"
            "\n"
            "/* Sezioni sinistra e destra */\n"
            ".sinistra {\n"
            "    border: 1px solid #0071e3;\n"
            "    padding: 1.5rem;\n"
            "    border-radius: 8px;\n"
            "    background: rgba(0, 113, 227, 0.05);\n"
            "}\n"
            "\n"
            ".destra {\n"
            "    border: 1px solid #a2845d;\n"
            "    padding: 1.5rem;\n"
            "    border-radius: 8px;\n"
            "    background: rgba(162, 132, 93, 0.05);\n"
            "}\n"
            "\n"
            ".spazio {\n"
            "    padding: 1rem;\n"
            "}\n"
            "\n"
            "/* Layout flex */\n"
            ".selezione {\n"
            "    display: flex;\n"
            "    gap: 3rem;\n"
            "    flex-wrap: wrap;\n"
            "    justify-content: center;\n"
            "    align-items: flex-start;\n"
            "}\n"
            "\n"
            ".container {\n"
            "    flex: 0 1 300px;\n"
            "    text-align: center;\n"
            "}\n"
            "\n"
            ".container-layout {\n"
            "    display: flex;\n"
            "    flex-direction: column;\n"
            "    align-items: center;\n"
            "    gap: 1.5rem;\n"
            "    flex: 0 1 auto;\n"
            "}\n"
            "\n"
            ".image-layout {\n"
            "    width: 100%;\n"
            "    max-width: 500px;\n"
            "    display: block;\n"
            "    border-radius: 8px;\n"
            "    border: 1px solid #e5e5e7;\n"
            "    margin: 0;\n"
            "    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n"
            "}\n"
            "\n"
            ".layout-info {\n"
            "    text-align: center;\n"
            "}\n"
            "\n"
            ".layout-info h2 {\n"
            "    margin: 0 0 0.5rem 0;\n"
            "    font-size: 1.5rem;\n"
            "}\n"
            "\n"
            ".layout-info p {\n"
            "    margin: 0;\n"
            "    font-size: 1rem;\n"
            "    color: #86868b;\n"
            "}\n"
            "\n"
            "/* Separatori - Minimal */\n"
            "hr {\n"
            "    border: none;\n"
            "    height: 1px;\n"
            "    background-color: #e5e5e7;\n"
            "    margin: 2rem 0;\n"
            "}\n"
            "\n"
            "/* Anteprima - Right column */\n"
            ".area-anteprima {\n"
            "    background: #ffffff;\n"
            "    border-radius: 8px;\n"
            "    border: 1px solid #e5e5e7;\n"
            "    padding: 1.5rem;\n"
            "    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);\n"
            "    position: sticky;\n"
            "    top: 2rem;\n"
            "    max-height: calc(100vh - 4rem);\n"
            "    overflow-y: auto;\n"
            "}\n"
            "\n"
            ".area-anteprima h2 {\n"
            "    margin-top: 0;\n"
            "}\n"
            "\n"
            ".blocco-renderizzato {\n"
            "    margin: 0.8rem 0;\n"
            "}\n"
            "\n"
            ".blocco-renderizzato h1 {\n"
            "    color: #1d1d1f;\n"
            "    font-size: 1.2rem;\n"
            "}\n"
            "\n"
            ".blocco-renderizzato h2 {\n"
            "    color: #1d1d1f;\n"
            "    font-size: 1rem;\n"
            "}\n"
            "\n"
            ".blocco-renderizzato p {\n"
            "    color: #424245;\n"
            "    font-size: 0.85rem;\n"
            "}\n"
            "\n"
            "/* Responsive - Ottimizzato per schermi grandi */\n"
            "@media (max-width: 1200px) {\n"
            "    h1 {\n"
            "        font-size: 1.6rem;\n"
            "    }\n"
            "    \n"
            "    .toolbar-aggiunta {\n"
            "        grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));\n"
            "    }\n"
            "}\n"
            "\n"
            "@media (max-width: 768px) {\n"
            "    body {\n"
            "        padding: 1rem;\n"
            "    }\n"
            "    \n"
            "    .main-container {\n"
            "        flex-direction: column;\n"
            "        gap: 1.5rem;\n"
            "    }\n"
            "    \n"
            "    .right-column {\n"
            "        flex: none;\n"
            "    }\n"
            "    \n"
            "    h1 {\n"
            "        font-size: 1.4rem;\n"
            "    }\n"
            "    \n"
            "    h2 {\n"
            "        font-size: 1rem;\n"
            "    }\n"
            "    \n"
            "    .area-di-lavoro {\n"
            "        padding: 1rem;\n"
            "    }\n"
            "    \n"
            "    .toolbar-aggiunta {\n"
            "        grid-template-columns: 1fr;\n"
            "    }\n"
            "    \n"
            "    .toolbar-aggiunta form {\n"
            "        flex-direction: column;\n"
            "    }\n"
            "    \n"
            "    .settings-bar {\n"
            "        flex-direction: column;\n"
            "    }\n"
            "    \n"
            "    .settings-bar form {\n"
            "        width: 100%;\n"
            "    }\n"
            "    \n"
            "    button {\n"
            "        width: 100%;\n"
            "    }\n"
            "    \n"
            "    .blocco-editor-controls {\n"
            "        grid-template-columns: repeat(2, 1fr);\n"
            "    }\n"
            "    \n"
            "    .selezione {\n"
            "        gap: 1rem;\n"
            "        flex-direction: column;\n"
            "    }\n"
            "    \n"
            "    .container-layout {\n"
            "        gap: 1rem;\n"
            "        width: 100%;\n"
            "    }\n"
            "    \n"
            "    .image-layout {\n"
            "        max-width: 100%;\n"
            "    }\n"
            "    \n"
            "    .area-anteprima {\n"
            "        position: static;\n"
            "        max-height: none;\n"
            "    }\n"
            "}\n"
            "    </style>\n"
            "</head>\n"
            "<body>"
        )

    if layout == "layout1":
        write_into_html(f'    <div class="area-anteprima" style="background: {colore_sfondo};">')
        for blocco in lista_blocchi:
            if blocco["tipo"] == "titolo":
                testo = f"""    <h1 style="font-family: Arial, Helvetica, sans-serif; font-size: 1.4em; border-bottom: 2px solid #333; padding-bottom: 0.6rem; color: {blocco.get("colore_titolo", "#000000")}; margin: 0;">{blocco["contenuto"]}</h1>"""
                write_into_html(testo)
            elif blocco["tipo"] == "testo":
                testo = f"""    <p style="font-family: Arial, Helvetica, sans-serif; font-size: 0.9em; line-height: 1.5; color: {blocco.get("colore_testo", "#000000")}; margin: 0.6rem 0;">{blocco["contenuto"]}</p>"""
                write_into_html(testo)
            elif blocco["tipo"] == "immagine":
                testo = f"""    <img src="{blocco["contenuto"]}" alt="Immagine" style="width: 100%; height: auto; display: block; border-radius: 6px; margin: 0.6rem 0;">"""
                write_into_html(testo)

    elif layout == "layout2":
        # --- Wrapper esterno con colore di sfondo ---
        write_into_html(f'    <div class="area-anteprima" style="background: {colore_sfondo};">')

        # --- Navbar: un link per ogni blocco di tipo "titolo" ---
        write_into_html('        <nav style="background: #222; padding: 0.8rem; display: flex; gap: 1rem; flex-wrap: wrap;">')
        for blocco in lista_blocchi:
            if blocco["tipo"] == "titolo":
                contenuto = blocco["contenuto"]
                etichetta = contenuto[:15] + "..." if len(contenuto) > 15 else contenuto
                write_into_html(f'            <a href="#" style="color: white; text-decoration: none; font-size: 0.8em;">{etichetta}</a>')
        write_into_html('        </nav>')

        # --- Contenuto: titoli, testo, immagini con logica "immagine pendente" ---
        write_into_html('        <div style="padding: 0.8rem;">')

        immagine_pendente = None

        for blocco in lista_blocchi:
            if blocco["tipo"] == "titolo":
                colore = blocco.get("colore_titolo", "#000000")
                testo = f'            <h2 style="font-size: 1.1em; margin-top: 0.8rem; border-left: 3px solid #222; padding-left: 0.8rem; color: {colore}; margin-bottom: 0.6rem;">{blocco["contenuto"]}</h2>'
                write_into_html(testo)

            elif blocco["tipo"] == "immagine":
                # Salva l'immagine: verrà affiancata al prossimo blocco testo
                immagine_pendente = blocco["contenuto"]

            elif blocco["tipo"] == "testo":
                colore = blocco.get("colore_testo", "#000000")
                if immagine_pendente:
                    # Immagine e testo affiancati in un div flex
                    write_into_html('            <div style="display: flex; gap: 0.8rem; align-items: flex-start; margin: 0.8rem 0;">')
                    write_into_html(f'                <img src="{immagine_pendente}" alt="Immagine" style="width: 40%; height: auto; object-fit: cover; border-radius: 6px;">')
                    write_into_html(f'                <p style="flex: 1; line-height: 1.5; color: {colore}; font-size: 0.85em;">{blocco["contenuto"]}</p>')
                    write_into_html('            </div>')
                    immagine_pendente = None
                else:
                    # Testo senza immagine abbinata
                    testo = f'            <p style="line-height: 1.5; color: {colore}; margin: 0.6rem 0; font-size: 0.85em;">{blocco["contenuto"]}</p>'
                    write_into_html(testo)

        # Se rimane un'immagine senza testo abbinato, mostrarla a larghezza piena
        if immagine_pendente:
            write_into_html(f'            <img src="{immagine_pendente}" alt="Immagine" style="width: 100%; height: auto; display: block; border-radius: 6px; margin: 0.8rem 0;">')

        write_into_html('        </div>')
        write_into_html('    </div>')

    write_into_html("</body>\n</html>")
    return